baseURL = 'https://example.org/'
locale = 'en-us'
title = 'Searby Meteor Cameras'
theme='PaperMod'
sectionPagesMenu = 'main'
[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
